# Site settings
title: Sinatra for Canberra
author: Emily McLean
url: https://sinatra-transport.com

homepage_image: cutout.jpg

keywords: Sinatra, MyWay+, MyWay, Canberra
description: Sinatra is a companion app for the Canberra MyWay+ network made by locals for locals.
locale: en_AU

theme:
  primary_color: fac1be

exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

feed:
  path: atom.xml

sass:
  style: compressed
  sass_dir: _sass

include: ['_pages']

